### ISSUE TITLE
same key in sequence and on its own results in 2 events

### ISSUE THREAD

**Issue by pirxpilot** [yields/k#29]
I am trying to use `k` to support something like github's `g c` (*goto code*) and `c`  (`create issue`) - 2 independent events - going to code does not trigger issue creation). However naive configuration works in such a way that whenever `g c` is pressed both handlers are called: one for `g c` sequence and one for a single `c` key.
I played with `k` tests and it seems that this is what's implemented at the moment. Is there any way of using `k` in which it does not behave like that (i.e. pressing `g c` does not trigger `c` handler). If not any ideas for a workaround? Here's to hoping I am just missing something obvious.

**Comment by yields** [comment]
fixed by b7284c914858045d8eb2d5ac89b25a9d431587a1
